### ISSUE TITLE
多卡训练中断

### ISSUE THREAD

**Issue by TE-Raven** [xiaoyichao/chagpt_simple_demo#1]
大佬我想问一下在用两张卡训练的时候发生了训练中断的情况，请问您在使用的适合发生过吗，或者有什么解决办法吗

global step 100 ( 6.67% ) , epoch: 1, loss: 5.81958, speed: 2.16 step/s, ETA: 00:10:48                                                                                                                    
global step 200 ( 13.33% ) , epoch: 1, loss: 5.65964, speed: 2.30 step/s, ETA: 00:09:25
global step 300 ( 20.00% ) , epoch: 1, loss: 5.40839, speed: 2.29 step/s, ETA: 00:08:44
global step 400 ( 26.67% ) , epoch: 1, loss: 5.28893, speed: 2.29 step/s, ETA: 00:08:00
global step 500 ( 33.33% ) , epoch: 1, loss: 5.10441, speed: 2.29 step/s, ETA: 00:07:17
Model has saved at ft_result/ptuning/model_500.
Evaluation Loss: 4.50876
Min eval loss has been updated: inf --> 4.50876
Best model has saved at ft_result/ptuning/model_best.
global step 600 ( 40.00% ) , epoch: 1, loss: 4.96669, speed: 1.71 step/s, ETA: 00:08:46
global step 700 ( 46.67% ) , epoch: 1, loss: 4.89438, speed: 1.70 step/s, ETA: 00:07:49
Used 00:11:38.

**Comment by xiaoyichao** [comment]
这歌项目是我fork 的，我用的是单卡。个人理解，这个项目中关于chatgpt 的部分，重点在于让大家理解原理，训练和效果，都不是最优的方案。建议时机使用的时候，使用deepspeed 框架

**Comment by xiaoyichao** [comment]
> 大佬我想问一下在用两张卡训练的时候发生了训练中断的情况，请问您在使用的适合发生过吗，或者有什么解决办法吗
> 
> global step 100 ( 6.67% ) , epoch: 1, loss: 5.81958, speed: 2.16 step/s, ETA: 00:10:48 global step 200 ( 13.33% ) , epoch: 1, loss: 5.65964, speed: 2.30 step/s, ETA: 00:09:25 global step 300 ( 20.00% ) , epoch: 1, loss: 5.40839, speed: 2.29 step/s, ETA: 00:08:44 global step 400 ( 26.67% ) , epoch: 1, loss: 5.28893, speed: 2.29 step/s, ETA: 00:08:00 global step 500 ( 33.33% ) , epoch: 1, loss: 5.10441, speed: 2.29 step/s, ETA: 00:07:17 Model has saved at ft_result/ptuning/model_500. Evaluation Loss: 4.50876 Min eval loss has been updated: inf --> 4.50876 Best model has saved at ft_result/ptuning/model_best. global step 600 ( 40.00% ) , epoch: 1, loss: 4.96669, speed: 1.71 step/s, ETA: 00:08:46 global step 700 ( 46.67% ) , epoch: 1, loss: 4.89438, speed: 1.70 step/s, ETA: 00:07:49 Used 00:11:38.

这项目是我fork 的，我用的是单卡。个人理解，这个项目中关于chatgpt 的部分，重点在于让大家理解原理。对于训练和效果，这个项目都不是最优的方案。建议实际使用的时候，使用deepspeed 框架

**Comment by TE-Raven** [comment]
感谢您的回复
